# get single review
query SingleReviewQuery($id: ID!) {
  review(id: $id) {
    rating
    content
  }
}

#Works the same for authors and reviews
query SingleAuthorQuery($id: ID!) {
  author(id: $id) {
    name
    verified
  }
}

query SingleGameQuery($id: ID!) {
  game(id: $id) {
    platform
    title
  }
}

# All reviews for a game
query getReviewsForSingleGame($id: ID!) {
  game(id: $id) {
    title
    reviews {
      rating
      content
    }
  }
}

# All reviews for an author

query getReviewsFromSingleAuthor($id: ID!) {
  author(id: $id) {
    name
    reviews {
      rating
      content
    }
  }
}
